extends:
  - standard
  - prettier
  - prettier/standard

parser: babel-eslint

plugins:
  - standard
  - prettier

globals:
  jasmine: true

env:
  browser: true

rules:
  no-var: error
  prefer-const: error
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: false
