language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
      - "node_modules"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - export NPM_REMOTE_VERSION=$(npm view kinka version)
  - export PACKAGE_NAME=$(node -p "require('./package.json').name")
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn unit-test
after_success:
  - ls -l
  - env
  - git remote rm origin
  - git remote add origin https://js2me:${GITHUB_TOKEN}@github.com/acacode/kinka.git
  - git remote set-url origin https://js2me:${GITHUB_TOKEN}@github.com/acacode/kinka.git
  - git fetch -p
  - git fetch
  - git symbolic-ref HEAD refs/heads/${TRAVIS_BRANCH}
  - git symbolic-ref HEAD
  - git remote show origin
  - git status
  - if [ ${TRAVIS_BRANCH} = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ];then
    git add dist && git commit -m "build release ${PACKAGE_VERSION} [ci skip]";
    git push --set-upstream origin ${TRAVIS_BRANCH};
    yarn git-release ${PACKAGE_VERSION};
    npm publish;
    rm -rf dist;
    git add dist && git commit -m "remove dist folder [ci skip]";
    git push --set-upstream origin ${TRAVIS_BRANCH};
    fi

